apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-role
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - deployments
  verbs:
  - get
  - list
  - watch
